### ISSUE TITLE
UI tests

### ISSUE THREAD

**Issue by balint355** [BME-MIT-IET/Emiliano-Jr-Andrew-Cole-Industries-iet-2019#22]
We should add new UI tests to increase their coverage

**Comment by balint355** [comment]
I fixed some tests in AccountsActivityTest which weren't annotated with "@Test". One of them was failing because it tried to use Espresso scrollTo() on a RecyclerView, which is not supported.

**Comment by balint355** [comment]
Added some new tests to test calculator keyboard when adding new transaction. It's now possible to press keys on the keyboard, this opens up the possibility of more tests.

**Comment by balint355** [comment]
AccountsActivityTest still has some problems, now 2 tests are failing which were fine earlier. Trying to fix.

**Comment by nkelemen18** [comment]
AccountsActivityTest -> testDeleteAccountWithSubaccounts failed because:

> AmbiguousViewMatcherException: matches multiple views in the hierarchy.

trying to fix it.

**Comment by nkelemen18** [comment]
testDeleteAccountWithSubAccounts fixed. The problem was that shouldIncludeFutureTransactionsInAccountBalance test created a transaction appeared on the "Recents" tab and the testDeleteAccountWithSubaccounts found more than one entry with the same text. Deleting the inserted transaction seems to solve the problem.
